import { readFileSync } from 'node:fs'
import { PUBLIC_URL } from '../config.js'
export const AIRDROP_JS = readFileSync(new URL('./airdrop.js', import.meta.url), 'utf8')
export function airdropPage() {
  return `<!doctype html><html lang="en"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Hunch · Supporter airdrop</title><meta name="description" content="A $$$ reward pool in HUNCH for people who supported Hunch before the October 2 snapshot. Submit existing posts for review.">
  <meta property="og:title" content="Hunch supporter airdrop"><meta property="og:image" content="${PUBLIC_URL}/brand/og.png"><meta name="twitter:card" content="summary_large_image">
  <link rel="icon" href="/brand/icon.svg"><link rel="stylesheet" href="/app.css">
  <script>try{document.documentElement.dataset.theme=localStorage.getItem('hunch-theme')||'dark'}catch{}</script>
  <style>
  .airdrop-wrap{max-width:1120px;margin:auto;padding:60px 24px 80px}.airdrop-hero{max-width:850px;padding:35px 0 44px}.airdrop-hero h1{font-size:clamp(42px,7vw,76px);letter-spacing:-.055em;line-height:1.05;margin:20px 0}.airdrop-hero p{color:var(--muted);font-size:18px;line-height:1.7;max-width:680px}.airdrop-pill{display:inline-block;border:1px solid var(--accent-line);background:var(--accent-soft);color:var(--accent);padding:8px 13px;border-radius:100px;font-size:13px}.airdrop-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-bottom:30px}.airdrop-stat{padding:24px;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.airdrop-stat strong{display:block;font-size:30px;letter-spacing:-.04em}.airdrop-stat span{color:var(--muted);font-size:14px}.airdrop-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:24px;align-items:start}.airdrop-card{padding:30px;background:var(--panel);border:1px solid var(--line);border-radius:18px}.airdrop-card h2{font-size:24px;margin:0 0 16px}.airdrop-card p,.airdrop-card li{color:var(--muted);line-height:1.7}.airdrop-card ol{padding-left:22px}.airdrop-card li{margin:12px 0}.airdrop-card label{display:block;margin:20px 0 8px;font-size:14px}.airdrop-card input,.airdrop-card textarea{width:100%;background:var(--bg-2);color:var(--text);border:1px solid var(--line-2);border-radius:10px;padding:13px;font:inherit}.airdrop-card textarea{min-height:130px;resize:vertical}.airdrop-card small{display:block;color:var(--muted);line-height:1.6;margin-top:8px}.airdrop-button{width:100%;margin-top:18px;border:0;background:var(--accent);color:var(--on-accent);border-radius:10px;padding:14px;font:inherit;font-weight:700;cursor:pointer}.airdrop-button:disabled{opacity:.45;cursor:not-allowed}.airdrop-outline{background:var(--panel-2);color:var(--text);border:1px solid var(--line-2)}#wallet-state{overflow-wrap:anywhere}#airdrop-status{margin-top:18px;line-height:1.7;white-space:pre-line;overflow-wrap:anywhere}.airdrop-terms{display:flex!important;gap:10px;line-height:1.6}.airdrop-terms input{width:18px;flex-shrink:0}.airdrop-footer{margin-top:35px;color:var(--muted);font-size:13px}.airdrop-nav{display:flex;align-items:center;justify-content:space-between;padding:22px 24px;max-width:1120px;margin:auto;gap:20px}.airdrop-nav img{width:145px}.airdrop-nav a{color:var(--muted);font-size:14px}.airdrop-nav div{display:flex;gap:18px}.airdrop-logo-light{display:none}:root[data-theme=light] .airdrop-logo-light{display:block}:root[data-theme=light] .airdrop-logo-dark{display:none}@media(max-width:720px){.airdrop-grid{grid-template-columns:1fr}.airdrop-stats{gap:8px}.airdrop-stat{padding:16px 10px}.airdrop-stat strong{font-size:23px}.airdrop-stat span{font-size:12px}.airdrop-wrap{padding-top:20px}.airdrop-card{padding:22px}.airdrop-nav{flex-wrap:wrap}.airdrop-hero{padding-top:20px}}
  .airdrop-button{backdrop-filter:none;-webkit-backdrop-filter:none}.airdrop-button:disabled{opacity:1;background:var(--panel-2);color:var(--muted);border:1px solid var(--line-2)}.airdrop-share{margin-top:28px;padding-top:24px;border-top:1px solid var(--line)}.airdrop-share canvas{width:100%;height:auto;border-radius:14px;margin-top:12px}.airdrop-share[hidden]{display:none}.airdrop-share-actions{display:flex;gap:10px;flex-wrap:wrap}.airdrop-share-actions a,.airdrop-share-actions button{margin-top:14px;padding:12px 16px;border-radius:10px;background:var(--accent);color:var(--on-accent);border:0;text-decoration:none;font-weight:600;font-size:14px}
  #wallet-picker{width:min(480px,calc(100% - 32px));background:var(--panel-solid);color:var(--text);border:1px solid var(--line-2);border-radius:18px;padding:26px}#wallet-picker::backdrop{background:rgba(0,0,0,.7)}#wallet-picker h2{margin:0 0 12px;font-size:24px}#wallet-picker p{color:var(--muted);line-height:1.6}#wallet-options{display:grid;gap:10px}.wallet-option,.wallet-open{display:block;width:100%;text-align:left;margin-top:10px;padding:14px;border:1px solid var(--line-2);border-radius:10px;background:var(--panel-2);color:var(--text);font:inherit;text-decoration:none}.wallet-option:hover,.wallet-open:hover{border-color:var(--accent)}#wallet-close{float:right;padding:6px 10px}#wallet-picker-status{white-space:pre-line;overflow-wrap:anywhere;color:var(--accent)}#wallet-state{white-space:pre-line;color:var(--muted)}
  </style></head><body>
  <header class="airdrop-nav"><a href="/" aria-label="Hunch home"><img class="airdrop-logo-dark" src="/brand/logo-dark.svg" alt="Hunch"><img class="airdrop-logo-light" src="/brand/logo-light.svg" alt="Hunch"></a><div><a href="/">Live console</a><a href="/watch">Open a watch</a><a href="https://x.com/hunchmode" target="_blank" rel="noopener noreferrer">@hunchmode ↗</a></div></header>
  <main class="airdrop-wrap"><section class="airdrop-hero"><span class="airdrop-pill">For the people who were here early</span><h1>You backed Hunch.<br><span style="color:var(--accent)">This is for you.</span></h1><p>A $$$ reward pool, paid in $HUNCH, for accounts that supported and posted about Hunch before the snapshot. Submit your existing posts for review. New posts do not qualify.</p></section>
  <section class="airdrop-stats" aria-label="Campaign details"><div class="airdrop-stat"><strong>$$$</strong><span>Total reward pool in $HUNCH</span></div><div class="airdrop-stat"><strong>Oct 2</strong><span>Snapshot · 11:47:12 am WAT</span></div><div class="airdrop-stat"><strong>In review</strong><span>Token claims are not open yet</span></div></section>
  <div class="airdrop-grid"><section class="airdrop-card"><h2>Register your existing support</h2><p>Connect the wallet you want to receive $HUNCH in, then submit posts published before the cutoff.</p><button id="connect-wallet" class="airdrop-button airdrop-outline" type="button">Connect wallet</button><small id="wallet-state" role="status">Use a browser wallet on desktop, or open this page inside your wallet’s browser.</small>
  <form id="airdrop-form"><label for="handle">Your X handle</label><input id="handle" name="handle" required maxlength="16" placeholder="@yourhandle" autocomplete="off" pattern="@?[A-Za-z0-9_]{1,15}">
  <label for="posts">Existing X post links</label><textarea id="posts" name="posts" required maxlength="6000" placeholder="https://x.com/yourhandle/status/…&#10;One post per line"></textarea><small>Up to 20 posts, published from September 18, 2026 at 11:12:26 pm WAT through October 2, 2026 at 11:47:12 am WAT.</small>
  <label class="airdrop-terms"><input id="consent" type="checkbox" required><span>I own this X account and wallet. I understand submissions are reviewed and do not guarantee a reward.</span></label>
  <button id="submit-entry" class="airdrop-button" type="submit" disabled>Sign & submit for review</button></form>
  <p id="airdrop-status" role="status" aria-live="polite"></p><button class="airdrop-button airdrop-outline" type="button" disabled>Claim $HUNCH · opens after review</button><small>No payment or token approval is required to register. We will never ask for your seed phrase.</small><section class="airdrop-share" id="share-reward" hidden><h2 id="share-title">Share your Hunch reward</h2><p id="share-description"></p><canvas id="reward-card" width="1200" height="675" role="img" aria-label="Your Hunch supporter reward card"></canvas><div class="airdrop-share-actions"><button id="download-card" type="button">Download card</button><a id="share-on-x" target="_blank" rel="noopener noreferrer">Post on X ↗</a></div><small>Download the image, then attach it to your X post. X does not attach the image automatically.</small><a id="claim-receipt" target="_blank" rel="noopener noreferrer" hidden>View confirmed payout ↗</a></section></section>
  <aside class="airdrop-card"><h2>How it works</h2><ol><li><strong>Existing support only.</strong> Original Hunch posts published before the fixed cutoff qualify for review. Copying, duplicate entries and purchased engagement do not qualify.</li><li><strong>Verify your account.</strong> After submitting, reply to one of your submitted posts with your confirmation code. This reply proves account ownership; it earns no additional reward.</li><li><strong>Review the evidence.</strong> We verify account ownership, posts and view evidence before publishing allocations. The cutoff fixes eligible post dates; view counts have not yet been independently captured.</li><li><strong>Claim your allocation.</strong> Approved supporters will receive a fixed $HUNCH allocation. The conversion rate and claim opening will be published before claims start.</li></ol><p>The reward formula is being finalized. The $$$ pool is separate from the creator bounty. Connecting a wallet does not automatically establish eligibility.</p><a href="https://x.com/hunchmode" target="_blank" rel="noopener noreferrer" style="color:var(--accent)">Follow official updates ↗</a></aside></div>
  <footer class="airdrop-footer">Robinhood Chain · $HUNCH<br><span style="overflow-wrap:anywhere">0x0976f3067dd97321b7ab269c5a2c290264f7046d</span><p>Free hunches. Paid proof.</p></footer></main><dialog id="wallet-picker" aria-labelledby="wallet-picker-title"><button id="wallet-close" type="button" aria-label="Close wallet picker">✕</button><h2 id="wallet-picker-title">Connect your wallet</h2><p id="wallet-picker-help">Choose your wallet below.</p><div id="wallet-options"></div><p id="wallet-picker-status" role="status" aria-live="polite"></p><div id="wallet-app-links"><p>On mobile, open this page inside your wallet app. On desktop, use a browser with a wallet extension.</p><a class="wallet-open" id="open-metamask" rel="noopener noreferrer">Open in MetaMask app ↗</a><a class="wallet-open" id="open-trust">Open in Trust Wallet app ↗</a><button class="wallet-option" id="copy-wallet-link" type="button">Copy page link for another browser</button></div></dialog><script src="/airdrop.js?v=mobile-submit-3" defer></script></body></html>`
}
