import type { EvidenceLine, Investigation } from '../core/types.js'
import { PUBLIC_URL } from '../config.js'
import { siteNavigation, SITE_CSS } from './navigation.js'
import { readFileSync } from 'node:fs'

export const REPORT_JS = readFileSync(new URL('./investigation-report.js', import.meta.url), 'utf8')
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!)
const money = (value: number) => `$${value.toFixed(value < 1 ? 4 : 2)}`
const url = (value: string) => /^https?:\/\//i.test(value) ? esc(value) : null
const labels: Record<string, string> = { funded: 'Queued for research', running: 'Research in progress', verifying: 'Checking the evidence', complete: 'Research complete', rejected: 'Verification needs review', failed: 'Research could not finish', supported: 'Supported', partially_supported: 'Partially supported', unsupported: 'Unsupported', unclear: 'Unclear' }
const date = (value: string | null) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('en-GB', { timeZone: 'UTC', day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) + ' UTC' : 'Not recorded'
export const reportIsRunning = (inv: Investigation) => ['funded', 'running', 'verifying'].includes(inv.status)

function evidence(title: string, lines: EvidenceLine[]) {
  return `<section class="card"><h2>${title}</h2>${lines.length ? `<ul class="report-evidence">${lines.map(line => `<li><p>${esc(line.finding)}</p><span class="muted">${esc(line.ref)} · ${esc(line.source)}</span>${url(line.url) ? ` · <a href="${url(line.url)}" target="_blank" rel="noopener noreferrer">Read source ↗</a>` : ''}</li>`).join('')}</ul>` : '<p class="muted">No evidence cited in this category.</p>'}</section>`
}

export function investigationReport(inv: Investigation) {
  const artifact = inv.artifact
  const accepted = inv.status === 'complete' && inv.acceptance?.accepted === true
  const working = reportIsRunning(inv)
  const progress = inv.status === 'funded' ? 0 : inv.status === 'running' ? 1 : inv.status === 'verifying' ? 2 : 3
  const steps = ['Budget allocated', 'Research sources', 'Verify findings', 'Research outcome']
  const verdict = accepted && artifact ? labels[artifact.status] : labels[inv.status] ?? inv.status
  return `<div class="report-head"><div class="eyebrow">Investigation ${esc(inv.id)}${inv.demo ? ' · DEMO FIXTURE' : ''}</div><h1>${esc(inv.claim)}</h1><p class="muted">Started ${date(inv.createdAt)}${inv.finishedAt ? ` · Finished ${date(inv.finishedAt)}` : ''}</p><div class="report-links">${inv.watchId ? `<a href="/watch?id=${encodeURIComponent(inv.watchId)}">← Follow this watch</a>` : ''}<a href="/api/investigations/${encodeURIComponent(inv.id)}?download=1">Download report JSON ↓</a></div></div>
  <ol class="watch-progress" aria-label="Investigation progress">${steps.map((step, i) => `<li class="${i < progress ? 'done' : i === progress ? 'current' : ''}"${i === progress ? ' aria-current="step"' : ''}><span>${i + 1}</span>${step}</li>`).join('')}</ol>
  <section class="card report-summary"><h2>${working ? 'Live research status' : 'Research result'}</h2><strong class="report-verdict">${esc(verdict)}</strong>${accepted && artifact ? `<p class="muted">${Math.round(artifact.confidence * 100)}% confidence · Hunch’s assessment of the evidence.</p>` : ''}${inv.status === 'rejected' ? '<p class="muted">The result did not pass Hunch’s acceptance checks. Treat the findings below as a draft awaiting review.</p>' : ''}${working ? '<p class="muted">This page updates as research and verification progress. Findings appear when the verifier finishes.</p>' : ''}${inv.error ? `<p class="err">${esc(inv.error)}</p>` : ''}<div class="stats report-stats"><div class="stat"><div class="v">${money(inv.spentUsd)}</div><div class="l">Actual research cost</div></div><div class="stat"><div class="v">${money(inv.maxBudgetUsd)}</div><div class="l">Maximum allocated</div></div><div class="stat"><div class="v">${inv.evidence.filter(doc => doc.ok).length}</div><div class="l">Sources retrieved</div></div><div class="stat"><div class="v">${inv.workers.filter(worker => worker.status === 'done').length}/${inv.workers.length}</div><div class="l">Worker steps completed</div></div></div></section>
  ${artifact ? `<section class="card"><h2>What Hunch found${accepted ? '' : ' · draft'}</h2><ul class="report-findings">${artifact.finding.map(finding => `<li>${esc(finding)}</li>`).join('')}</ul><p class="muted">Next step: <strong>${esc(artifact.recommendedAction)}</strong></p></section><div class="report-grid">${evidence('Evidence for', artifact.evidenceFor)}${evidence('Evidence against', artifact.evidenceAgainst)}</div><section class="card"><h2>What remains unknown</h2>${artifact.unknowns.length ? `<ul class="report-findings">${artifact.unknowns.map(unknown => `<li>${esc(unknown)}</li>`).join('')}</ul>` : '<p class="muted">No additional unknowns were recorded by the verifier.</p>'}</section><details class="card" data-report-detail="reasoning"><summary>Origin and verification reasoning</summary><p>${esc(artifact.rationale)}</p><p class="muted">First seen: ${date(artifact.origin.firstSeen)} · ${esc(artifact.origin.source)}${url(artifact.origin.url) ? ` · <a href="${url(artifact.origin.url)}" target="_blank" rel="noopener noreferrer">Read original source ↗</a>` : ''}</p>${inv.acceptance ? `<ul class="report-findings">${inv.acceptance.checks.map(check => `<li>${check.ok ? '✓' : '✕'} ${esc(check.label)} <span class="muted">${esc(check.detail)}</span></li>`).join('')}</ul>` : ''}</details>` : ''}`
}

export function investigationPage(inv: Investigation) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hunch · Investigation ${esc(inv.id)}</title><meta name="description" content="${esc(inv.claim)}"><meta property="og:title" content="Hunch investigation"><meta property="og:url" content="${PUBLIC_URL}/investigations/${encodeURIComponent(inv.id)}"><meta property="og:image" content="${PUBLIC_URL}/brand/og.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/brand/icon.svg"><link rel="stylesheet" href="/app.css?v=watch-reports-1"><script>try{document.documentElement.dataset.theme=localStorage.getItem('hunch-theme')||'dark'}catch{}</script><style>${SITE_CSS}</style></head><body>${siteNavigation('/investigations')}<main class="site-main report-page"><a class="report-back" href="/investigations">← All investigations</a><div id="investigation-report" data-id="${esc(inv.id)}" data-running="${reportIsRunning(inv)}">${investigationReport(inv)}</div><p id="report-update" class="muted" role="status" aria-live="polite">${reportIsRunning(inv) ? 'Live report · checks for updates every 6 seconds' : 'Research finished'}</p><button id="report-refresh" class="small" type="button">Refresh report</button></main><footer class="site-footer">Free hunches. Paid proof. · <a href="https://x.com/hunchmode">@hunchmode</a></footer><script src="/investigation-report.js?v=1" defer></script></body></html>`
}
